<?php

namespace Copal\RoomBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HubRepository extends EntityRepository
{
}
