<?php

namespace Copal\RoomBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TalkerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TalkerRepository extends EntityRepository
{
}
