<?php

namespace Copal\UniversityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HumanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HumanRepository extends EntityRepository
{
}
